#include QMK_KEYBOARD_H

#define _LAYER0 0
#define _LAYER1 1

enum custom_keycodes {
    LAYER0 = SAFE_RANGE,
    LAYER1,
};

enum { TD_1_F1, TD_2_F2, TD_3_F3, TD_4_F4, TD_5_F5, TD_6_F6, TD_7_F7, TD_8_F8, TD_9_F9, TD_0_F10, TD_MINS_F11, TD_EQL_F12, TD_F13_F14, TD_GRV_F15, TD_DEL_F16, TD_LCTL_ESC };

qk_tap_dance_action_t tap_dance_actions[] = {[TD_1_F1] = ACTION_TAP_DANCE_DOUBLE(KC_1, KC_F1), [TD_2_F2] = ACTION_TAP_DANCE_DOUBLE(KC_2, KC_F2), [TD_3_F3] = ACTION_TAP_DANCE_DOUBLE(KC_3, KC_F3), [TD_4_F4] = ACTION_TAP_DANCE_DOUBLE(KC_4, KC_F4), [TD_5_F5] = ACTION_TAP_DANCE_DOUBLE(KC_5, KC_F5), [TD_6_F6] = ACTION_TAP_DANCE_DOUBLE(KC_6, KC_F6), [TD_7_F7] = ACTION_TAP_DANCE_DOUBLE(KC_7, KC_F7), [TD_8_F8] = ACTION_TAP_DANCE_DOUBLE(KC_8, KC_F8), [TD_9_F9] = ACTION_TAP_DANCE_DOUBLE(KC_9, KC_F9), [TD_0_F10] = ACTION_TAP_DANCE_DOUBLE(KC_0, KC_F10), [TD_MINS_F11] = ACTION_TAP_DANCE_DOUBLE(KC_MINS, KC_F11), [TD_EQL_F12] = ACTION_TAP_DANCE_DOUBLE(KC_EQL, KC_F12), [TD_F13_F14] = ACTION_TAP_DANCE_DOUBLE(KC_F13, KC_F14), [TD_GRV_F15] = ACTION_TAP_DANCE_DOUBLE(KC_GRV, KC_F15), [TD_DEL_F16] = ACTION_TAP_DANCE_DOUBLE(KC_DEL, KC_F16), [TD_LCTL_ESC] = ACTION_TAP_DANCE_DOUBLE(KC_LCTL, KC_ESC)};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

    [_LAYER0] = LAYOUT(KC_ESC, TD(TD_1_F1), TD(TD_2_F2), TD(TD_3_F3), TD(TD_4_F4), TD(TD_5_F5), TD(TD_6_F6), TD(TD_7_F7), TD(TD_8_F8), TD(TD_9_F9), TD(TD_0_F10), TD(TD_MINS_F11), TD(TD_EQL_F12), KC_BSPC, TD(TD_GRV_F15), KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, KC_RBRC, KC_BSLS, TD(TD_DEL_F16), TD(TD_LCTL_ESC), KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_ENT, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT, KC_UP, TD(TD_F13_F14), KC_LGUI, KC_LALT, KC_SPC, KC_RALT, KC_RCTL, MO(1), KC_LEFT, KC_DOWN, KC_RGHT),

    [_LAYER1] = LAYOUT(KC_GRV, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_TRNS, KC_TRNS, KC_TRNS, KC_MUTE, KC_VOLU, KC_MPLY, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_PSCR, KC_SLCK, KC_PAUS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_MPRV, KC_VOLD, KC_MNXT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_HOME, KC_PGUP, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_END, KC_PGDN, KC_TRNS, KC_TRNS, KC_PGUP, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_HOME, KC_PGDN, KC_END)

};
